[package]
name = "tab_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audrey = "0.3.0"
cute = "0.3.0"
minimp3 = "0.5.1"
rustfft = "6.2.0"
